export interface Agenda {
  goal?: string;
  clock?: 4 | 6 | 8;
  progress?: number;
  allies: string[];
  enemies: string[];
  assets: string[];
  vulnerabilities: string[];
}

export const agendas: Record<string, Agenda> = {
  valerie: {
    goal: 'Hold Pitax for Nova Valoria and seat a loyal council',
    clock: 8,
    progress: 1,
    allies: ['The PCs, who placed her on the throne', 'Jhofre Vascari', 'Joravin Pyathe'],
    enemies: ['Eliste Strocalle', 'Kharne Vareel', 'Alasen'],
    assets: ['The throne and the palace, the House of a Hundred Doors', 'The PCs’ mandate as regent', 'Council applicants vetted by the PCs', 'Reputation for honor no house can buy'],
    vulnerabilities: ['Nova Valoria is far away and slow to help', 'Still recovering from imprisonment', 'No patience for humor or intrigue', 'A Brevic noble among houses who fled Brevoy'],
  },
  salvarri: {
    goal: 'Restore Cattanei primacy as Pitax’s founding house',
    clock: 8,
    progress: 2,
    allies: ['Drey Yarness, keeper of the old Cattanei keep', 'Valerie'],
    enemies: ['Xapiri Yasmina', 'Eliste Strocalle'],
    assets: ['Descent from Cesare Cattanei, the Silver Fox', 'Cathedral raised from the original Cattanei keep', 'Minority stake in the Serpent’s Breath Trade House', 'A bard’s gift for swaying the council'],
    vulnerabilities: ['Ludov Cattanei’s treachery still stains the name', 'Xapiri holds the controlling stake', 'Poorest house at the council table', 'Troutmouth workers and sailors loathe the Bandit Houses'],
  },
  xapiri: {
    goal: 'Buy a council seat to prove infernal leadership',
    clock: 6,
    progress: 1,
    allies: [],
    enemies: ['House Thrune', 'Salvarri Cattanei'],
    assets: ['Controlling interest in the Serpent’s Breath Trade House', 'Trade House revenue diverted to her research', 'Sorcery of a 10th-level sorcerer'],
    vulnerabilities: ['Secretly exiled from Cheliax by House Thrune', 'A faked Chelish agent sighting can drive her out', 'Pitaxians distrust a Chelish buyer of a founding house', 'Knows little of the region’s politics'],
  },
  gasperre: {
    goal: 'Reclaim the Iron Fox and Liacenza primacy',
    clock: 8,
    progress: 2,
    allies: ['Conspirators who met at the Falling Star', 'Joravin Pyathe, the brothers’ appointee'],
    enemies: ['Eliste Strocalle', 'Pitax Wardens holding the Iron Fox Armory'],
    assets: ['Sarain vineyards and most orchards around Pitax', 'The Falling Star inn', 'Standing as an early foe of Irovetti'],
    vulnerabilities: ['Youth and inexperience', 'Irovetti’s signed deed to Liacenza holdings survives', 'Sole heir to a house that lost its rulers'],
  },
  eliste: {
    goal: 'Hide her Irovetti ties and hold a seat',
    clock: 6,
    progress: 2,
    allies: ['Kharne Vareel and Pitax’s criminals', 'Irovetti loyalists in hiding'],
    enemies: ['Liacenza Family', 'Cattanei Family', 'Vascari Family', 'Valerie'],
    assets: ['Darkwind Trade House and its overland trade', 'Secure warehouse', 'Blackmail gathered on the other houses'],
    vulnerabilities: ['Helped put Irovetti on the throne', 'Palace papers that name her', 'Bribes and protection eat most of her income', 'No one in Pitax trusts the Strocalles'],
  },
  temur: {
    goal: 'Keep his Wardens armed, paid and above the law',
    clock: 6,
    progress: 2,
    allies: ['His unit of loyal Wardens', 'Joravin Pyathe, who needs enforcers on the docks'],
    enemies: ['Ingras Quill', 'Gasperre Liacenza', 'Drey Yarness', 'Kharne Vareel and the Dealers'],
    assets: ['One disciplined unit of Wardens, armed and drilled', 'The Iron Fox Armory and its stores', 'Patrol records that name every informer, fence and smuggler in Pitax', 'Warden swordplay backed by occult magic'],
    vulnerabilities: ['Pitax hates and fears the Wardens', 'His signature fills the Black Cells arrest warrants', 'Ingras Quill’s journal names his men', 'The Liacenza claim to the Armory'],
  },
  jhofre: {
    goal: 'Win the council’s river trade for the Vascaris',
    clock: 6,
    progress: 2,
    allies: ['Sailors who owe the Vascaris allegiance', 'Valerie'],
    enemies: ['Eliste Strocalle', 'Joravin Pyathe, whose tariff office checks the Vascari schedule'],
    assets: ['Riversong Trade House schedules every ship’s trade', 'Power to deny ships official import slots', 'Contacts the length of the Sellen River'],
    vulnerabilities: ['Other houses and citizens treat him as an outsider', 'Troutmouth workers and sailors loathe the Bandit Houses'],
  },
  kharne: {
    goal: 'Keep the Dealers’ trade alive under the council',
    clock: 6,
    progress: 2,
    allies: ['Allied drug dealers, alchemists and crooked merchants', 'Eliste Strocalle'],
    enemies: ['The Bandit Houses', 'Valerie', 'Ghare Leotos'],
    assets: ['Drug laboratory in the Rose Tower', 'Illicit market', 'War-weary citizens still buying'],
    vulnerabilities: ['Lost Irovetti’s protection', 'Palace ledgers of his “sin tax” payments', 'Leads a loose coalition of criminals'],
  },
  drey: {
    goal: 'Win Calistria a voice on the council',
    clock: 6,
    progress: 3,
    allies: ['Admirers who want a leader other than the king', 'Ingras Quill'],
    enemies: ['Eliste Strocalle', 'Remnant Pitax Wardens'],
    assets: ['Calistria’s Cathedral, Pitax’s oldest and strongest faith', 'Knows more about the city than any priest should', 'Credit for Calistria’s vengeance on Irovetti'],
    vulnerabilities: ['Followers push him to rule himself', 'Sharp tongue grates on Valerie’s decorum', 'Ghouls infest the Tower of the Fallen'],
  },
  ghare: {
    goal: 'Heal Irovetti’s victims and bless the new order',
    clock: 6,
    progress: 1,
    allies: ['Emboldened Desnan clergy', 'Ingras Quill'],
    enemies: ['Ghouls of the Tower of the Fallen', 'Kharne Vareel'],
    assets: ['Temple of Desna shrine', 'Runs the city’s festivities on Desna’s holy days', 'Scrolls to give grateful allies'],
    vulnerabilities: ['Small congregation', 'Most sailors ignore the temple', 'Old age'],
  },
  atlee: {
    goal: 'Win the Red Crescent Theater free of debt',
    clock: 6,
    progress: 2,
    allies: ['Red Crescent rebels who stayed', 'A wealthy Taldan patron', 'Atalia Gitaren and the Academy of the Arts'],
    enemies: ['Troupe members who served the king'],
    assets: ['Red Crescent Theater', 'A star singer back on stage'],
    vulnerabilities: ['Theater debt now owed to the council', 'Troupe schism outlives the king', 'Lost her star to Asmeranda Ilata’s guild', 'Talented actors avoid the theater'],
  },
  asmeranda: {
    goal: 'Win the city’s working artists a council voice apart from the Academy',
    clock: 6,
    progress: 1,
    allies: ['Red Crescent rebels who followed her out', 'Street players and tavern singers of Troutmouth', 'Ghare Leotos, who needs performers for his festivals'],
    enemies: ['Gedovius', 'Troupe members who served the king'],
    assets: ['A star voice', 'Testimony about the Black Cells', 'The sympathy of a city that watched her vanish'],
    vulnerabilities: ['Scars of the Black Cells', 'No hall, no purse and no experience of politics', 'Breaking with Atlee Quinge, who made her a star'],
  },
  irovetti: {
    allies: ['Eliste Strocalle', 'Alasen and the Catspaw Marauders', 'Annamede Belavarah', 'Wardens who stayed at their posts'],
    enemies: ['Liacenza Family', 'Drey Yarness', 'Nyrissa, whom he deceived'],
    assets: ['The palace, the House of a Hundred Doors', 'Iron Fox Trade House and the Liacenza deed', 'Mindrender baton and rod of razors', 'Warehouses bought cheap through mind control'],
    vulnerabilities: ['A deed signed under magical coercion', 'Briar’s recovery hidden from Nyrissa', 'Agents murdered to hide Briar’s discovery', 'Murdered the Liacenza brothers in the Black Cells'],
  },
  koth: {
    allies: ['Pitax Wardens'],
    enemies: ['PCs who unseated him', 'Kin of his joust “self-defense” victims'],
    assets: ['Vacant Captain of the Guard post', 'Vacant Midnight Joust championship', 'Payroll chest of gold and healing potions'],
    vulnerabilities: ['Unpunished killings the Wardens covered up'],
  },
  jurrg: {
    allies: ['Mercenaries, hill giant Tusker riders and wyverns'],
    enemies: ['Nova Valoria and its armies', 'Ilora Nuski'],
    assets: ['Pitax’s field armies, now unpaid and masterless', 'War machines on the city walls'],
    vulnerabilities: ['Unpaid mercenaries raiding the countryside', 'A war that emptied the treasury'],
  },
  alasen: {
    goal: 'Strike back at the PCs and the kingdom with Annamede Belavarah',
    clock: 6,
    progress: 1,
    allies: ['Catspaw Marauders', 'Annamede Belavarah'],
    enemies: ['Rulers of Hajoth Hakados', 'The PCs', 'Valerie'],
    assets: ['Catspaw Marauder armies', 'Gold from Pitax’s treasury', 'Weretiger forms, invisibility and Pounce'],
    vulnerabilities: ['The Marauders break if she dies', 'No paymaster now', 'Exiled after a failed coup'],
  },
  engelidis: {
    allies: [],
    enemies: [],
    assets: ['Lagoon holding the depleted treasury', 'Underwater doors to river and grotto'],
    vulnerabilities: ['A secret river entrance into the palace', 'Roald Celinnas has heard of a shapechanging consort'],
  },
  nunzio: {
    goal: 'Return to public life once it is safe',
    clock: 4,
    progress: 0,
    allies: ['Rushlight contestants who trusted his rulings'],
    enemies: ['Ingras Quill'],
    assets: ['The best-known voice in Pitax', 'A reputation for fair judging'],
    vulnerabilities: ['Served Irovetti in public', 'In hiding', 'Wears no armor'],
  },
  velemandr: {
    goal: 'Come out of hiding and carry messages for the new council',
    clock: 4,
    progress: 0,
    allies: [],
    enemies: [],
    assets: ['A fleet-footed runner’s speed', 'Knows the roads to Nova Valoria'],
    vulnerabilities: ['Carried Irovetti’s treacherous invitation', 'In hiding'],
  },
  wardens: {
    goal: 'Escape punishment and remain the city guard',
    clock: 6,
    progress: 2,
    allies: ['Temur Ganbold', 'Nunzio Arpaia'],
    enemies: ['Ingras Quill', 'Drey Yarness', 'Former Pitaxian rebels'],
    assets: ['Iron Fox Armory barracks and gear', 'Occult magic backing their swordplay'],
    vulnerabilities: ['One unit left of a whole city guard', 'Loyal to Temur Ganbold alone', 'Killed Ingras Quill’s son', 'The Liacenzas claim the Armory'],
  },
  annamede: {
    goal: 'Strike back at the PCs and the kingdom with Alasen',
    clock: 6,
    progress: 1,
    allies: ['Alasen and the Catspaw Marauders', 'Pitax’s adoring public'],
    enemies: ['The PCs, the bard Jean above all', 'Valerie', 'Eliste Strocalle'],
    assets: ['Unbeaten Rushlight boasting champion', 'The Common Square stage', 'Bodyguards who travel with her'],
    vulnerabilities: ['Loyal first to herself', 'Took Irovetti’s patronage', 'Spied on Nova Valoria'],
  },
  atalia: {
    goal: 'Take full control of the Academy of the Arts',
    clock: 6,
    progress: 3,
    allies: ['Talented students and teachers', 'Cayid Caconna', 'Atlee Quinge and the Red Crescent Troupe'],
    enemies: ['The hack faculty Irovetti hired', 'Asmeranda Ilata, who claims the city’s artists for her guild'],
    assets: ['Genuine talent and a wonderful singing voice', 'Hidden works ready to show the city'],
    vulnerabilities: ['Academy funding came from the crown', 'Fears backlash on her students'],
  },
  cayid: {
    goal: 'Collect the crown’s debt for his sculptures',
    clock: 4,
    progress: 1,
    allies: ['Atalia Gitaren'],
    enemies: ['Artistic rivals'],
    assets: ['Stolen key to the palace service entrance', 'Hidden compartments in gargoyles across Pitax', 'Commissions from nobles across the River Kingdoms'],
    vulnerabilities: ['Holds a key stolen from the palace', 'Works alone at night'],
  },
  roald: {
    goal: 'Add Irovetti’s palace books to the Crow’s Feather',
    clock: 4,
    progress: 1,
    allies: ['Scholars and would-be academics who fill the inn'],
    enemies: ['Would-be book thieves', 'Xapiri Yasmina'],
    assets: ['Vast library of writings', 'Uncanny sense for would-be thieves', 'Hidden wizardry'],
    vulnerabilities: ['Hides his magic and Brevic ancestry'],
  },
  ingras: {
    goal: 'See her son’s killers among the Wardens hanged',
    clock: 6,
    progress: 1,
    allies: ['Rebels she sheltered in her basement', 'Drey Yarness'],
    enemies: ['Pitax Wardens', 'Nunzio Arpaia'],
    assets: ['Journal of palace patrols and Warden faces', 'Gratitude of the liberated city'],
    vulnerabilities: ['Grief over her murdered son', 'Lost her palace delivery trade', 'Wants revenge more than power'],
  },
  joravin: {
    goal: 'Bring law to the docks under the council',
    clock: 6,
    progress: 1,
    allies: ['Gasperre Liacenza, heir to the brothers who appointed him', 'Valerie'],
    enemies: ['Jhofre Vascari', 'Smugglers working the black market'],
    assets: ['Tariff office watching all goods on the docks', 'Trusted arbiter in Bandit House disputes', 'Records of every house’s shipments'],
    vulnerabilities: ['No city guard to enforce his rulings', 'None of the Bandit Houses likes him', 'Enforced Irovetti’s arbitrary tax changes'],
  },
  saufie: {
    goal: 'Win council coin to keep the Tusks lit',
    clock: 4,
    progress: 1,
    allies: ['Jhofre Vascari'],
    enemies: [],
    assets: ['Eastern lighthouse on the Devil’s Tusks', 'View of all harbor traffic', 'Signal lights that can guide or mislead ships'],
    vulnerabilities: [],
  },
  duclarion: {
    goal: 'Find a patron to keep the Menagerie in Pitax',
    clock: 4,
    progress: 1,
    allies: ['The Ohka Brothers'],
    enemies: [],
    assets: ['Charmed dinosaurs, rare animals and supernatural beasts', 'Enchantment magic'],
    vulnerabilities: ['Beasts and ogres stay calm only under her enchantments', 'No Rushlight festival to pay her'],
  },
  ohka: {
    goal: 'Stay with Madame Duclarion and the Menagerie',
    clock: 4,
    progress: 2,
    allies: ['Madame Duclarion'],
    enemies: [],
    assets: ['Ogre brawn'],
    vulnerabilities: ['Kept calm only by Duclarion’s enchantments'],
  },
};
