// Pull character data and art from the sibling pitax-factions repo, which stays the single source.
// The copies are committed so CI and release builds never need the sibling checkout.
//   npm run sync -- [--from <path to pitax-factions>]
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const fromFlag = process.argv.indexOf('--from');
const SOURCE = resolve(fromFlag > 0 ? process.argv[fromFlag + 1] : join(ROOT, '..', '..', 'pitax-factions'));
if (!existsSync(SOURCE)) {
  console.error(`pitax-factions not found at ${SOURCE} — pass --from <path>`);
  process.exit(1);
}

const DATA_FILES = ['pitax.ts', 'bios.ts', 'backgrounds.ts', 'agendas.ts', 'cases.ts', 'consequences.ts'];
const dataOut = join(ROOT, 'src', 'pitax');
mkdirSync(dataOut, { recursive: true });
for (const file of DATA_FILES) copyFileSync(join(SOURCE, 'src', 'data', file), join(dataOut, file));

const art = join(SOURCE, 'source art');
const talentOut = join(ROOT, 'assets', 'talent');
const portraitOut = join(ROOT, 'assets', 'portraits');
const thumbOut = join(portraitOut, 'thumbs');
const audioOut = join(ROOT, 'assets', 'audio');
for (const dir of [talentOut, thumbOut, audioOut]) mkdirSync(dir, { recursive: true });

for (const file of ['pitax-stage-tall.webp', 'poster.webp']) copyFileSync(join(art, 'talent', file), join(talentOut, file));
// The X's render at ~80px, so the 800–1250px originals only cost download time.
for (const file of ['x-off.webp', 'x-on.webp', 'x-on-glow.webp']) {
  await sharp(join(art, 'talent', file)).resize(256, 256).webp({ quality: 90 }).toFile(join(talentOut, file));
}

// The download holds several buzzes; the first one ends in the quiet gap before 0.664s.
execFileSync('ffmpeg', [
  '-y', '-loglevel', 'error',
  '-i', join(art, 'talent', 'audio.wav'),
  '-t', '0.664',
  '-af', 'afade=t=out:st=0.634:d=0.03',
  '-c:a', 'libopus', '-b:a', '96k',
  join(audioOut, 'buzzer.ogg'),
]);

const portraits = readdirSync(join(art, 'portraits')).filter((f) => f.endsWith('.webp')).sort();
for (const file of portraits) {
  const src = join(art, 'portraits', file);
  await sharp(src).resize({ height: 1200 }).webp({ quality: 84, alphaQuality: 90 }).toFile(join(portraitOut, file));
  await sharp(src).resize({ height: 240 }).webp({ quality: 80 }).toFile(join(thumbOut, file));
}

const names = portraits.map((f) => basename(f, '.webp'));
writeFileSync(
  join(dataOut, 'portraits.ts'),
  `// Generated by scripts/sync-pitax.ts.\nexport const portraitNames = new Set<string>(${JSON.stringify(names, null, 2)});\n`,
);

console.log(`✓ synced ${DATA_FILES.length} data files, ${portraits.length} portraits, 5 talent images, the buzzer from ${SOURCE}`);
