// Pull character data and art from the sibling pitax-factions repo, which stays the single source.
// The copies are committed so CI and release builds never need the sibling checkout.
//   npm run sync -- [--from <path to pitax-factions>] [--force]
// Assets rebuild only when their source's contents change; --force rebuilds them all, e.g. after changing encode settings.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const fromFlag = process.argv.indexOf('--from');
const SOURCE = resolve(fromFlag > 0 ? process.argv[fromFlag + 1] : join(ROOT, '..', '..', 'pitax-factions'));
if (!existsSync(SOURCE)) {
  console.error(`pitax-factions not found at ${SOURCE} — pass --from <path>`);
  process.exit(1);
}

const DATA_FILES = ['pitax.ts', 'bios.ts', 'backgrounds.ts', 'agendas.ts', 'cases.ts', 'consequences.ts', 'problems.ts'];
const dataOut = join(ROOT, 'src', 'pitax');
mkdirSync(dataOut, { recursive: true });
for (const file of DATA_FILES) copyFileSync(join(SOURCE, 'src', 'data', file), join(dataOut, file));

const force = process.argv.includes('--force');
const HASHES = join(ROOT, 'scripts', 'sync-pitax.hashes.json');
const previous: Record<string, string> = existsSync(HASHES) ? JSON.parse(readFileSync(HASHES, 'utf8')) : {};
const hashes: Record<string, string> = {};
let built = 0;
let checked = 0;

// Re-encoding the buzzer changes its bytes on every run (Ogg stream serials are random), so unchanged assets stay put.
// Contents decide, not timestamps: art copied in from the generator keeps its original, older mtime.
async function asset(src: string, out: string, make: (src: string, out: string) => unknown): Promise<void> {
  checked++;
  const key = relative(ROOT, out);
  hashes[key] = createHash('sha1').update(readFileSync(src)).digest('hex');
  if (!force && existsSync(out) && previous[key] === hashes[key]) return;
  await make(src, out);
  built++;
}

const art = join(SOURCE, 'source art');
const talentOut = join(ROOT, 'assets', 'talent');
const portraitOut = join(ROOT, 'assets', 'portraits');
const thumbOut = join(portraitOut, 'thumbs');
const tokenOut = join(ROOT, 'assets', 'tokens');
const audioOut = join(ROOT, 'assets', 'audio');
for (const dir of [talentOut, thumbOut, tokenOut, audioOut]) mkdirSync(dir, { recursive: true });

await asset(join(art, 'talent', 'poster.webp'), join(talentOut, 'poster.webp'), copyFileSync);
const stage = join(art, 'talent', 'pitax-gotit.png');
await asset(stage, join(talentOut, 'pitax-gotit.webp'), (src, out) => sharp(src).webp({ quality: 82 }).toFile(out));
await asset(stage, join(talentOut, 'stage-thumb.webp'), (src, out) => sharp(src).resize(300, 300).webp({ quality: 80 }).toFile(out));
// The X's render at roughly 60–130px, so the 800–1250px originals only cost download time.
for (const file of ['x-off.webp', 'x-on.webp', 'x-on-glow.webp']) {
  await asset(join(art, 'talent', file), join(talentOut, file), (src, out) => sharp(src).resize(256, 256).webp({ quality: 90 }).toFile(out));
}

// The download holds several buzzes; the first one ends in the quiet gap before 0.664s.
await asset(join(art, 'talent', 'audio.wav'), join(audioOut, 'buzzer.ogg'), (src, out) =>
  execFileSync('ffmpeg', [
    '-y', '-loglevel', 'error',
    '-i', src,
    '-t', '0.664',
    '-af', 'afade=t=out:st=0.634:d=0.03',
    '-c:a', 'libopus', '-b:a', '96k',
    out,
  ]),
);

const portraits = readdirSync(join(art, 'portraits')).filter((f) => f.endsWith('.webp')).sort();
for (const file of portraits) {
  const src = join(art, 'portraits', file);
  await asset(src, join(portraitOut, file), (src, out) => sharp(src).resize({ height: 1200 }).webp({ quality: 84, alphaQuality: 90 }).toFile(out));
  await asset(src, join(thumbOut, file), (src, out) => sharp(src).resize({ height: 240 }).webp({ quality: 80 }).toFile(out));
}

// A token draws at about one grid square, so 512px stays sharp at full zoom without shipping the 1254px originals.
const tokens = readdirSync(join(art, 'tokens')).filter((f) => f.endsWith('.webp')).sort();
for (const file of tokens) {
  await asset(join(art, 'tokens', file), join(tokenOut, file), (src, out) => sharp(src).resize(512, 512).webp({ quality: 85 }).toFile(out));
}

writeFileSync(HASHES, `${JSON.stringify(hashes, null, 2)}\n`);

const names = portraits.map((f) => basename(f, '.webp'));
writeFileSync(
  join(dataOut, 'portraits.ts'),
  `// Generated by scripts/sync-pitax.ts.\nexport const portraitNames = new Set<string>(${JSON.stringify(names, null, 2)});\n`,
);

console.log(`✓ synced ${DATA_FILES.length} data files, ${portraits.length} portraits and ${tokens.length} tokens from ${SOURCE}; rebuilt ${built} of ${checked} assets`);
